### PR TITLE
Create project skeleton

### PR DESCRIPTION
**Pull request by adam-dej**
[Review on Reviewable](https://reviewable.io/reviews/fmfi-svt-deadlock/reader-sw/1)

### CODE REVIEW

**Comment by AnotherKamila** [comment]
Note: I did not really read the board, HAL and MCU configuration -- if there are errors, they will be much easier to notice with the actual hardware than by looking at the file.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[boards/reader-revA/board.c, line 1 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tE2qLT4VD4RpIk46_:-K8tE2qMS94aD1WIkt4B:-498656931) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/boards/reader-revA/board.c#L1)):_
For files board.[ch], do the originals tend to change between ChibiOS versions? If yes, you may want to add some version info into the header.

---

_[boards/reader-revA/board.c, line 18 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8t5LokK26S6g-dhPe9:-K8t5LokK26S6g-dhPeA:1952043225) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/boards/reader-revA/board.c#L18)):_
"This file" presumably.

---

_[chconf.h, line 1 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tDXJEYtLU9PEVraDX:-K8tDXJEYtLU9PEVraDY:1883983029) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/chconf.h#L1)):_
I presume this may change with chibiOS releases => add version info.

---

_[Makefile, line 236 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tJa_UNd2BivbOGNjV:-K8tJa_VND1eRGxml1uX:-1119970625) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/Makefile#L236)):_
Shouldn't the 0x08000000 be a variable? (I assume it depends on the MCU or something)

---

_[README.md, line 20 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tKFzSU_sZ9wjFv4M7:-K8tKFzSU_sZ9wjFv4M8:-642794532) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/README.md#L20)):_
remove "the"

---

_[src/main.c, line 16 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tLCLqA43t4JNzo4vy:-K8tLCLrJQi6GdvV_XHr:-414674140) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/src/main.c#L16)):_
Note: if I understand correctly, you don't need a loop in `main()` as an idle thread is created by default. I assume this is here just for now.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-:-K8tCiED__1Zd3BmNDYK:21004435)_

**Comment by adam-dej** [comment]
Review status: 10 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

_[boards/reader-revA/board.c, line 1 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tE2qLT4VD4RpIk46_:-K8tLwSz0IvZBmwyXl7v:-2043010560) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/boards/reader-revA/board.c#L1)):_
I really have no idea. I just left the original header intact. This was taken form a demo project. I have no version information about the demo project, as it may be independent of the OS version. Even if, I suspect that this file will stay compatible with newer versions.

---

_[chconf.h, line 1 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tDXJEYtLU9PEVraDX:-K8tMDwcH2DeOfTGh6pz:194562840) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/chconf.h#L1)):_
This is, again, the original header. Actually this file shouldn't change dramatically as well. But I'm not sure.

---

_[src/main.c, line 16 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tLCLqA43t4JNzo4vy:-K8tMZjWB12LOILf8n_D:562620607) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/src/main.c#L16)):_
If I understand things correctly main() **is** the idle thread. It mustn't exit.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1)_

**Comment by AnotherKamila** [comment]
Review status: 10 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

_[chconf.h, line 1 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tDXJEYtLU9PEVraDX:-K8tOssG4ccG720d4_oM:-1149223489) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/chconf.h#L1)):_
New chibiOS versions may bring new options (but they will have sane defaults, so whatever).

---

_[src/main.c, line 16 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tLCLqA43t4JNzo4vy:-K8tOQ5rOD60VWMX1Jce:-2133533997) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/src/main.c#L16)):_
Check chconf.h:104.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1)_

**Comment by adam-dej** [comment]
Review status: 10 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/main.c, line 16 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tLCLqA43t4JNzo4vy:-K8tPLofUXqHNuxWFrYT:333662970) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/src/main.c#L16)):_
You are right.  But "Note that the main() function is not meant to return, the system would stop." --ChibiOS/RT 3.0 - The Ultimate Guide

Therefore it is not the idle thread, but cannot return either. Maybe I should change `chconf.h`:104 to make `main()` the idle thread?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1)_

**Comment by AnotherKamila** [comment]
Review status: 10 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/main.c, line 16 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tLCLqA43t4JNzo4vy:-K8tQBQuFPjKhDmMi0SF:1922986864) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/src/main.c#L16)):_
Try it! If it works without the loop, remove it. If not, set that to false or whatever.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1)_

**Comment by adam-dej** [comment]
Review status: 10 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/main.c, line 16 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tLCLqA43t4JNzo4vy:-K8tR4jcLfD3u3ZOVQXO:1252578481) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/b7eaa66f40279e1369b249a0da1cdca713aab113/src/main.c#L16)):_
I did, it doesn't work without the loop. I will change `chconf.h` to make main() the idle thread. I'll add some explanatory comment as well.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/main.c, line 18 [r3]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1#-K8tZQTtwYXgxmBk4Ht9:-K8tZQTtwYXgxmBk4HtA:1333391999) ([raw file](https://github.com/fmfi-svt-deadlock/reader-sw/blob/f60eb5661defb2bc785379f6bcd5eeec048c798d/src/main.c#L18)):_
Perhaps add "TODO: send MCU to low-power sleep" or something.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/reader-sw/1)_

**Pull request merged**
